# Site settings
title: Vikas Reddy
author:
  name: Vikas Reddy
  email: vkasire2@jhu.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Vikas Reddy's personal website

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:slug

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-detail"